# Numpys

In [1]:
import numpy as np

In [2]:
lists = [2,3,4,5]

In [4]:
list2 = np.array([2,3,4,5])
list2

array([2, 3, 4, 5])

In [5]:
# differenece in arr with numpy arr

In [6]:
biglist = list(range(1000000))
big_Arr = np.array(1000000)

In [7]:
%timeit [ x**2 for x in biglist]

459 ms ± 4.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%timeit big_Arr**2

971 ns ± 3.46 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
##creating  arrays

In [13]:
a = np.array([1,2,3]) ##1D arr
b = np.array([[1,2,3],[1,3,4]])## 2D arr

In [15]:
print(a)
b

[1 2 3]


array([[1, 2, 3],
       [1, 3, 4]])

In [16]:
## arr with default value

In [19]:
print(np.zeros((2,3)))
##row -colm

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.full((2,3),6))
#row-clm-elem

[[6 6 6]
 [6 6 6]]


In [21]:
##identity array

In [22]:
print(np.eye(3))
#row = colm = 3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1]:
    ##25-06-2026
import numpy as np

In [2]:
M = np.array([[1,2,3],[2,3,4]])

In [3]:
M.size

6

In [4]:
M.shape

(2, 3)

In [5]:
M.dtype

dtype('int64')

In [6]:
##change datatype

In [8]:
N = np.array([1,2,3] , dtype = np.float64)

In [9]:
N.dtype

dtype('float64')

In [10]:
print(N[2])

3.0


In [11]:
print(M[0][0])


1


In [12]:
##slice
M[0:2]


array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
print(M[0:2])

[[1 2 3]
 [2 3 4]]


In [14]:
# vector operation

In [15]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a/b)

[0.1 0.1 0.1 0.1]


In [17]:
print(a @ b) #A.B = |a|.|b|/cos theta

300


# pandas

In [18]:
##whenever wworking with tabular data..

In [19]:
import pandas as pd
import numpy as np

In [20]:
s = pd.Series([12,20,30])

In [21]:
s

0    12
1    20
2    30
dtype: int64

In [22]:
# custom index

In [24]:
df = pd.Series([1500,1400,400,600],
               index = ["India","china","USA","pakistan"],
               name = "population_million"
              )

In [25]:
df

India       1500
china       1400
USA          400
pakistan     600
Name: population_million, dtype: int64

In [27]:
df1 = pd.DataFrame({
    "name" : ["Asha","Bill","Chen","billa"],
    "dept" : ["IT","HR","IT","FINANCE"],
    "age" : [25,32,27,29],
    "salary" : [52000,23000,4500,10]
})

In [29]:
df1

,name,dept,age,salary
0,Asha,IT,25,52000
1,Bill,HR,32,23000
2,Chen,IT,27,4500
3,billa,FINANCE,29,10


In [31]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      object
 1   dept    4 non-null      object
 2   age     4 non-null      int64 
 3   salary  4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes


In [32]:
df1.shape


(4, 4)

In [34]:
print(list(df1.columns))

['name', 'dept', 'age', 'salary']


In [35]:
df1.describe()

,age,salary
count,4.000000,4.000000
mean,28.250000,19877.500000
std,2.986079,23613.485377
min,25.000000,10.000000
25%,26.500000,3377.500000
50%,28.000000,13750.000000
75%,29.750000,30250.000000
max,32.000000,52000.000000


In [45]:
df1 = df1.set_index("name")

In [47]:
print(df1.loc["Bill"])

dept         HR
age          32
salary    23000
Name: Bill, dtype: object


In [48]:
messy = pd.DataFrame({ ## messy.isnull().sum()
    "product" : ["pen","book","car","scooter"],
    "price" : [20,np.nan,30,np.nan],
    "rating" : [4.1,4.5,4.8,np.nan]
})

In [49]:
messy

,product,price,rating
0,pen,20.0,4.1
1,book,NaN,4.5
2,car,30.0,4.8
3,scooter,NaN,NaN


In [50]:
messy.isnull().sum()

product    0
price      2
rating     1
dtype: int64

In [51]:
#skewed --- median(eg - price)
# data is symmetric --- mean(eg - rating)
# categorical --- mode (eg - product name)

In [53]:
cleaning = messy.copy()

In [56]:
cleaning["price"] = cleaning["price"].fillna(cleaning["price"].median())

In [57]:
cleaning["rating"] = cleaning["rating"].fillna(cleaning["rating"].mean())

In [58]:
cleaning

,product,price,rating
0,pen,20.0,4.100000
1,book,25.0,4.500000
2,car,30.0,4.800000
3,scooter,25.0,4.466667
